version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - ./.env
    expose:
      - "5000"
    command: gunicorn --workers 4 --bind 0.0.0.0:5000 main:app

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
